# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adam-lorenz/Main/Vivado_Projects/loopback_project/loopback_project.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
